version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpass1
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: testpass1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
